version: '3.4'

#create a volume for the my sql container.To ensure Data persists after my sql container is stopped
volumes:
  datafiles:

services:
  #DataBase Service
  sqlserver:
    build:
      context: /home/ubuntu/app11/mssql
      dockerfile: /home/ubuntu/app11/mssql/Dockerfile
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Qwerty@12345"
      MSSQL_PID: Developer
    hostname: "sqlserver"
    ports:
      - "1433:1433"
    volumes:
      - datafiles:/var/opt/mssql
      - "~/sql-scripts/setup.sh:/scripts/entrypoint.sh"
    restart: always

  api:
    build:
      context: .
      #Use the DockerFile in that Directory
      dockerfile: Dockerfile
    #This Service Depends on the database service specifed above
    depends_on: 
      - sqlserver
    #Map port 8888 in the docker container to port 80 in the Api
    ports:
      - "5000:80"
    hostname: "apiserver"
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DBServer: "sqlserver"
    

        